config/routes.rb
Rails.application.routes.draw do
  resources :galaxy_generators, only: [:new, :create]
  resources :moons
  resources :planet_types
  resources :planets
  resources :stars
  resources :galaxies
  resources :quadrants
  resources :systems
  resources :sub_sectors
  resources :sectors

end

app/models/quadrant.rb
class Quadrant < ActiveRecord::Base
  belongs_to :galaxy
  has_many :sectors, dependent: :destroy

  def self.generate_quadrants(galaxy,
                        quadrant_x,
                        quadrant_y,
                        sector_x,
                        sector_y,
                        sub_sector_x,
                        sub_sector_y)

    puts "Quadrant X: " + quadrant_x if Rails.env.development?

    qx = 1
    while qx <= (quadrant_x.to_i) do
      qy = 1

      while qy <= (quadrant_y.to_i) do
        quadrant = galaxy.quadrants.build(name: "Quadrant" + qx.to_s + qy.to_s,
                                          quadrant_x: qx,
                                          quadrant_y: qy)

        if quadrant.save
          sector = Sector.generate_sectors(quadrant,
                                   sector_x,
                                   sector_y,
                                   sub_sector_x,
                                   sub_sector_y)

          if !sector
            quadrant.errors = sector.errors
            return quadrant
          end
        else
          return quadrant
        end

        qy += 1
      end

      qx += 1
    end

    quadrant
  end
end

app/controllers/quadrants_controller.rb
class QuadrantsController < ApplicationController
  before_action :set_quadrant, only: [:show, :edit, :update, :destroy]

  # GET /quadrants
  # GET /quadrants.json
  def index
    @quadrants = Quadrant.all
  end

  # GET /quadrants/1
  # GET /quadrants/1.json
  def show
    @sectors = @quadrant.sectors.all
  end

  # GET /quadrants/new
  def new
    @quadrant = Quadrant.new
  end

  # GET /quadrants/1/edit
  def edit
  end

  # POST /quadrants
  # POST /quadrants.json
  def create
    @quadrant = Quadrant.new(quadrant_params)

    respond_to do |format|
      if @quadrant.save
        format.html { redirect_to @quadrant, notice: 'Quadrant was successfully created.' }
        format.json { render :show, status: :created, location: @quadrant }
      else
        format.html { render :new }
        format.json { render json: @quadrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quadrants/1
  # PATCH/PUT /quadrants/1.json
  def update
    respond_to do |format|
      if @quadrant.update(quadrant_params)
        format.html { redirect_to @quadrant, notice: 'Quadrant was successfully updated.' }
        format.json { render :show, status: :ok, location: @quadrant }
      else
        format.html { render :edit }
        format.json { render json: @quadrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quadrants/1
  # DELETE /quadrants/1.json
  def destroy
    @quadrant.destroy
    respond_to do |format|
      format.html { redirect_to quadrants_url, notice: 'Quadrant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quadrant
      @quadrant = Quadrant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quadrant_params
      params.require(:quadrant).permit(:universe_id, :name, :quadrant_x, :quadrant_y)
    end
end

app/helpers/quadrants_helper.rb
module QuadrantsHelper
end

app/views/quadrants/_form.html.erb
<%= form_for(@quadrant) do |f| %>
  <% if @quadrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quadrant.errors.count, "error") %> prohibited this quadrant from being saved:</h2>

      <ul>
      <% @quadrant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :universe_id %><br>
    <%= f.number_field :universe_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quadrant_x %><br>
    <%= f.number_field :quadrant_x %>
  </div>
  <div class="field">
    <%= f.label :quadrant_y %><br>
    <%= f.number_field :quadrant_y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quadrants/_quadrant.html.erb
<li id="quadrant-<%= quadrant.id %>">
  <%= link_to quadrant.name, quadrant_path(quadrant) %>
</li>

app/views/quadrants/edit.html.erb
<h1>Editing Quadrant</h1>

<%= render 'form' %>

<%= link_to 'Show', @quadrant %> |
<%= link_to 'Back', quadrants_path %>

app/views/quadrants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quadrants</h1>

<table>
  <thead>
    <tr>
      <th>Universe</th>
      <th>Name</th>
      <th>Quadrant x</th>
      <th>Quadrant y</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quadrants.each do |quadrant| %>
      <tr>
        <td><%= quadrant.universe_id %></td>
        <td><%= quadrant.name %></td>
        <td><%= quadrant.quadrant_x %></td>
        <td><%= quadrant.quadrant_y %></td>
        <td><%= link_to 'Show', quadrant %></td>
        <td><%= link_to 'Edit', edit_quadrant_path(quadrant) %></td>
        <td><%= link_to 'Destroy', quadrant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quadrant', new_quadrant_path %>

app/views/quadrants/new.html.erb
<h1>New Quadrant</h1>

<%= render 'form' %>

<%= link_to 'Back', quadrants_path %>

app/views/quadrants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Galaxy:</strong>
  <%= link_to @quadrant.galaxy_id, galaxy_path(@quadrant.galaxy) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @quadrant.name %>
</p>

<p>
  <strong>Quadrant x:</strong>
  <%= @quadrant.quadrant_x %>
</p>

<p>
  <strong>Quadrant y:</strong>
  <%= @quadrant.quadrant_y %>
</p>

<% if @quadrant.sectors.any? %>
    <p>
      <strong><%= pluralize(@sectors.count, 'Sectors') %>:</strong>
    <ol>
      <%= render @sectors %>
    </ol>
    </p>
<% end %>

<%= link_to 'Edit', edit_quadrant_path(@quadrant) %> |
<%= link_to 'Back', galaxy_path(@quadrant.galaxy) %>