config/routes.rb
Rails.application.routes.draw do
  resources :galaxy_generators, only: [:new, :create]
  resources :moons
  resources :planet_types
  resources :planets
  resources :stars
  resources :galaxies
  resources :quadrants
  resources :systems
  resources :sub_sectors
  resources :sectors

end

app/models/sub_sector.rb
class SubSector < ActiveRecord::Base
  belongs_to :sector
  has_one :system, dependent: :destroy

  def self.generate_subsectors(sector,
                         sub_sector_x,
                         sub_sector_y)

    ssx = 1
    while ssx <= sub_sector_x.to_i
      ssy = 1

      while ssy <= sub_sector_y.to_i
        sub_sector = sector.sub_sectors.build(subsector_x: ssx,
                                              subsector_y: ssy)

        if sub_sector.save
          # TODO Magic Number!!!
          if Random.rand(1..100) <= 8
            system = System.generate_system(sub_sector)

            unless system
              sub_sector.errors = system.errors
              return sub_sector
            end

            puts "System generated in subsector: " + ssx.to_s + " " + ssy.to_s if Rails.env.development?
          else
            puts "No system in: " + ssx.to_s + " " + ssy.to_s if Rails.env.development?
          end
        else
          return sub_sector
        end

        ssy += 1
      end

      ssx += 1
    end

    sub_sector
  end
end

app/controllers/sub_sectors_controller.rb
class SubSectorsController < ApplicationController
  before_action :set_sub_sector, only: [:show, :edit, :update, :destroy]

  # GET /sub_sectors
  # GET /sub_sectors.json
  def index
    @sub_sectors = SubSector.all
  end

  # GET /sub_sectors/1
  # GET /sub_sectors/1.json
  def show
    @systems = @sub_sector.system
  end

  # GET /sub_sectors/new
  def new
    @sub_sector = SubSector.new
  end

  # GET /sub_sectors/1/edit
  def edit
  end

  # POST /sub_sectors
  # POST /sub_sectors.json
  def create
    @sub_sector = SubSector.new(sub_sector_params)

    respond_to do |format|
      if @sub_sector.save
        format.html { redirect_to @sub_sector, notice: 'Sub sector was successfully created.' }
        format.json { render :show, status: :created, location: @sub_sector }
      else
        format.html { render :new }
        format.json { render json: @sub_sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_sectors/1
  # PATCH/PUT /sub_sectors/1.json
  def update
    respond_to do |format|
      if @sub_sector.update(sub_sector_params)
        format.html { redirect_to @sub_sector, notice: 'Sub sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_sector }
      else
        format.html { render :edit }
        format.json { render json: @sub_sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_sectors/1
  # DELETE /sub_sectors/1.json
  def destroy
    @sub_sector.destroy
    respond_to do |format|
      format.html { redirect_to sub_sectors_url, notice: 'Sub sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_sector
      @sub_sector = SubSector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_sector_params
      params.require(:sub_sector).permit(:sector_id, :subsector_X, :subsector_Y)
    end
end

app/helpers/sub_sectors_helper.rb
module SubSectorsHelper
end

app/views/sub_sectors/_form.html.erb
<%= form_for(@sub_sector) do |f| %>
  <% if @sub_sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_sector.errors.count, "error") %> prohibited this sub_sector from being saved:</h2>

      <ul>
      <% @sub_sector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sector_id %><br>
    <%= f.number_field :sector_id %>
  </div>
  <div class="field">
    <%= f.label :subsector_X %><br>
    <%= f.number_field :subsector_X %>
  </div>
  <div class="field">
    <%= f.label :subsector_Y %><br>
    <%= f.number_field :subsector_Y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_sectors/_sub_sector.html.erb
<li id="sub_sector-<%= sub_sector.id %>">
  <%= link_to 'SubSector ' + sub_sector.subsector_x.to_s + ', ' + sub_sector.subsector_y.to_s, sub_sector_path(sub_sector) %>
  <% if sub_sector.system %>
    (<%= link_to sub_sector.system.name, system_path(sub_sector.system) %>)
  <% end %>
</li>

app/views/sub_sectors/edit.html.erb
<h1>Editing Sub Sector</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_sector %> |
<%= link_to 'Back', sub_sectors_path %>

app/views/sub_sectors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sub Sectors</h1>

<table>
  <thead>
    <tr>
      <th>Sector</th>
      <th>Subsector x</th>
      <th>Subsector y</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_sectors.each do |sub_sector| %>
      <tr>
        <td><%= sub_sector.sector_id %></td>
        <td><%= sub_sector.subsector_x %></td>
        <td><%= sub_sector.subsector_y %></td>
        <td><%= link_to 'Show', sub_sector %></td>
        <td><%= link_to 'Edit', edit_sub_sector_path(sub_sector) %></td>
        <td><%= link_to 'Destroy', sub_sector, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub sector', new_sub_sector_path %>

app/views/sub_sectors/new.html.erb
<h1>New Sub Sector</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_sectors_path %>

app/views/sub_sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sector:</strong>
  <%= link_to @sub_sector.sector_id, sector_path(@sub_sector.sector) %>
</p>

<p>
  <strong>Subsector x:</strong>
  <%= @sub_sector.subsector_x %>
</p>

<p>
  <strong>Subsector y:</strong>
  <%= @sub_sector.subsector_y %>
</p>

<% if @sub_sector.system %>
    <p>
      <strong>Systems</strong>
    <ol>
      <%= render @systems %>
    </ol>
    </p>
<% end %>

<%= link_to 'Edit', edit_sub_sector_path(@sub_sector) %> |
<%= link_to 'Back', sector_path(@sub_sector.sector) %>