config/routes.rb
Rails.application.routes.draw do
  resources :galaxy_generators, only: [:new, :create]
  resources :moons
  resources :planet_types
  resources :planets
  resources :stars
  resources :galaxies
  resources :quadrants
  resources :systems
  resources :sub_sectors
  resources :sectors

end

app/models/star.rb
class Star < ActiveRecord::Base
  belongs_to :system

  def self.generate_star(system, star_letter)
    rand_solar_class = Random.rand() * 100
    # solar_class = 'M'
    # solar_mass = 0

    # TODO Magic Number!!!
    case rand_solar_class
      when (0..0.00003)
        # O class star
        solar_class = 'O'

        # TODO Magic Number!!!
        solar_mass = Random.rand(160..1100) / 10.0
      when (0.00003..0.13)
        # B class star
        solar_class = 'B'

        # TODO Magic Number!!!
        solar_mass = Random.rand(21..160) / 10.0
      when (0.13..0.73) #.6%
        # A class star
        solar_class = 'A'

        # TODO Magic Number!!!
        solar_mass = Random.rand(140..210) / 100.0
      when (0.73..3.73) #3%
        # F class star
        solar_class = 'F'

        # TODO Magic Number!!!
        solar_mass = Random.rand(104..140) / 100.0
      when (3.73..11.45) #7.6% / 7.72% adjusted for rounding
        # G class star
        solar_class = 'G'

        # TODO Magic Number!!!
        solar_mass = Random.rand(80..104) / 100.0
      when (11.45..23.55) #12.1%
        # K class star
        solar_class = 'K'

        # TODO Magic Number!!!
        solar_mass = Random.rand(45..80) / 100.0
      else # 76.45%
        # M class star
        solar_class = 'M'

        # TODO Magic Number!!!
        solar_mass = Random.rand(8..45) / 100.0
    end

    puts 'Solar Class Roll: ' + rand_solar_class.to_s + ' Solar class: ' + solar_class + 'Solar mass: ' + solar_mass.to_s if Rails.env.development?

    # TODO Magic Number!!!
    if(solar_mass < 0.43) # Brown dwarf
      luminosity = 0.23 * (solar_mass ** 2.3)
    elsif(solar_mass < 2) # 0.43 < solar_mass < 2
      luminosity = solar_mass ** 4
    elsif(solar_mass < 20) # 2 < solar_mass < 20
      luminosity = 1.5 * (solar_mass ** 3.5)
    else # Solar mass is >= 20
      luminosity = solar_mass * 3200
    end

    # TODO Magic Number!!!
    diameter = solar_mass ** 0.74

    # TODO Magic Number!!!
    surface_temperature = solar_mass ** 0.505

    star = Star.new(system_id: system.id,
                    name: "Star " + system.id.to_s + star_letter,
                    luminosity: luminosity,
                    mass: solar_mass,
                    diameter: diameter,
                    surface_temperature: surface_temperature,
                    spectral_class: solar_class
    )

    if star.save
      star
    else
      puts "Failed to generate star!" if Rails.env.development?
      false
    end
  end

  def self.get_star_energy(star, distance)
    temp = Converter.convert(:temperature, star.surface_temperature, :solar_temperatures, :kelvin)
    radius = Converter.convert(:distance, star.diameter, :solar_diameters, :km) / 2.0
    orbital_distance = Converter.convert(:distance, distance, :au, :km)
    energy = temp * Math.sqrt(radius / (2.0 * orbital_distance))

    puts "Surface Temperature: " + temp.to_s + "K" if Rails.env.development?
    puts "Size/Distance Factor: ("+ radius.to_s + " / 2 * " + orbital_distance.to_s + ") " + (radius / (2.0 * orbital_distance)).to_s if Rails.env.development?
    puts "Star Energy: " + energy.to_s if Rails.env.development?
    energy
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  before_action :set_star, only: [:show, :edit, :update, :destroy]

  # GET /stars
  # GET /stars.json
  def index
    @stars = Star.all
  end

  # GET /stars/1
  # GET /stars/1.json
  def show
  end

  # GET /stars/new
  def new
    @star = Star.new
  end

  # GET /stars/1/edit
  def edit
  end

  # POST /stars
  # POST /stars.json
  def create
    @star = Star.new(star_params)

    respond_to do |format|
      if @star.save
        format.html { redirect_to @star, notice: 'Star was successfully created.' }
        format.json { render :show, status: :created, location: @star }
      else
        format.html { render :new }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stars/1
  # PATCH/PUT /stars/1.json
  def update
    respond_to do |format|
      if @star.update(star_params)
        format.html { redirect_to @star, notice: 'Star was successfully updated.' }
        format.json { render :show, status: :ok, location: @star }
      else
        format.html { render :edit }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stars/1
  # DELETE /stars/1.json
  def destroy
    @star.destroy
    respond_to do |format|
      format.html { redirect_to stars_url, notice: 'Star was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_star
      @star = Star.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def star_params
      params.require(:star).permit(:name, :system_id, :luminosity, :mass, :diameter, :surface_temperature)
    end
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/views/stars/_form.html.erb
<%= form_for(@star) do |f| %>
  <% if @star.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@star.errors.count, "error") %> prohibited this star from being saved:</h2>

      <ul>
      <% @star.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :system_id %><br>
    <%= f.number_field :system_id %>
  </div>
  <div class="field">
    <%= f.label :luminosity %><br>
    <%= f.text_field :luminosity %>
  </div>
  <div class="field">
    <%= f.label :mass %><br>
    <%= f.text_field :mass %>
  </div>
  <div class="field">
    <%= f.label :diameter %><br>
    <%= f.text_field :diameter %>
  </div>
  <div class="field">
    <%= f.label :surface_temperature %><br>
    <%= f.text_field :surface_temperature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stars/_star.html.erb
<li id="star-<%= star.id %>">
  <%= link_to star.name, star_path(star) %>
</li>

app/views/stars/edit.html.erb
<h1>Editing Star</h1>

<%= render 'form' %>

<%= link_to 'Show', @star %> |
<%= link_to 'Back', stars_path %>

app/views/stars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>System</th>
      <th>Luminosity</th>
      <th>Mass</th>
      <th>Diameter</th>
      <th>Surface temperature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stars.each do |star| %>
      <tr>
        <td><%= star.name %></td>
        <td><%= star.system_id %></td>
        <td><%= star.luminosity %></td>
        <td><%= star.mass %></td>
        <td><%= star.diameter %></td>
        <td><%= star.surface_temperature %></td>
        <td><%= link_to 'Show', star %></td>
        <td><%= link_to 'Edit', edit_star_path(star) %></td>
        <td><%= link_to 'Destroy', star, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Star', new_star_path %>

app/views/stars/new.html.erb
<h1>New Star</h1>

<%= render 'form' %>

<%= link_to 'Back', stars_path %>

app/views/stars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @star.name %>
</p>

<p>
  <strong>System:</strong>
  <%= link_to @star.system.name, system_path(@star.system) %>
</p>

<p>
  <strong>Luminosity:</strong>
  <%= @star.luminosity %>
</p>

<p>
  <strong>Mass:</strong>
  <%= @star.mass %>
</p>

<p>
  <strong>Diameter:</strong>
  <%= @star.diameter %>
</p>

<p>
  <strong>Surface temperature:</strong>
  <%= @star.surface_temperature %>
</p>

<%= link_to 'Edit', edit_star_path(@star) %> |
<%= link_to 'Back', system_path(@star.system) %>