config/routes.rb
Rails.application.routes.draw do
  resources :galaxy_generators, only: [:new, :create]
  resources :moons
  resources :planet_types
  resources :planets
  resources :stars
  resources :galaxies
  resources :quadrants
  resources :systems
  resources :sub_sectors
  resources :sectors

end

app/models/planet.rb
class Planet < ActiveRecord::Base
  belongs_to :system
  belongs_to :planet_type
  has_many :moons, class_name: "Planet",
           foreign_key: "parent_planet_id",
           primary_key: "id",
           dependent: :destroy
  has_many :ores,
           dependent: :destroy
  belongs_to :parent_planet, class_name: "Planet",
             foreign_key: "parent_planet_id",
             primary_key: "id"

  default_scope -> { order(average_orbit: :asc) }

  def self.generate_planets(system, solar_mass)
    # starting_orbit = 0
    # current_orbit = 0
    previous_orbit = 0

    if system.habitable_zone_inner.nil? || system.habitable_zone_inner == 0 || system.habitable_zone_outer.nil? || system.habitable_zone_outer == 0
      starting_orbit = current_orbit = system.frost_line + Random.rand()
    else
      starting_orbit = current_orbit = Random.rand(system.habitable_zone_inner..system.habitable_zone_outer)
    end

    while current_orbit >= system.inner_orbit_limit do
      if (previous_orbit == 0 || (previous_orbit - current_orbit) > 0.15) # make sure orbits aren't too close
        calculate_planet_info(system, current_orbit, solar_mass)
      end

      previous_orbit = current_orbit

      # TODO Magic Numbers!!!
      current_orbit = current_orbit / Random.rand(1.4..2.0)

      puts "Previous Orbit: " + previous_orbit.to_s + " Current Orbit: " + current_orbit.to_s if Rails.env.development?
    end

    # TODO Magic Numbers!!!
    current_orbit = starting_orbit * Random.rand(1.4..2.0)
    previous_orbit = starting_orbit

    while current_orbit <= system.outer_orbit_limit do
      if (previous_orbit == 0 || (current_orbit - previous_orbit) > 0.15) # make sure orbits aren't too close
        calculate_planet_info(system, current_orbit, solar_mass)
      end

      previous_orbit = current_orbit

      # TODO Magic Numbers!!!
      current_orbit = current_orbit * Random.rand(1.4..2.0)
      puts "Previous Orbit: " + previous_orbit.to_s + " Current Orbit: " + current_orbit.to_s if Rails.env.development?
    end
  end

  def self.calculate_planet_info(system, orbit, solar_mass)
    mass = 0
    radius = 0
    density = 0
    # TODO Magic number!!!
    eccentricity = Random.rand(0.0..0.1)

    if system.forbidden_zone_outer.nil? || orbit > system.forbidden_zone_outer
      if system.forbidden_zone_inner.nil? || orbit < system.forbidden_zone_inner # orbit is outside the forbidden zone
        planet_roll = Random.rand(1..100)

        if orbit >= system.frost_line
          # More gas giants outside of Frost Line

          # TODO Magic Numbers!!!
          case planet_roll
            when (1..40)
              # Gas giant
              if planet_roll.in?(1..30)
                planet_type = PlanetType.find_by(name: 'Gas Giant').id
                mass = Random.rand(10.0..4132.0)
                radius = Math.log10(10 * mass) + Random.rand(1.5..5.0)

                # Gas giants more massive than 2Mj collapse at 11 Re, so adjust it to max out somewhere around there
                if mass > 635.0
                  if radius > 11.0
                    radius = 10.5 + Random.rand()
                  end
                end

                density = mass / (radius ** 3)
              else
                # Gas Dwarf

                planet_type = PlanetType.find_by(name: 'Gas Dwarf').id
                mass = Random.rand(1.0..20.0)
                radius = Math.log10(10 * mass) + Random.rand(0.5..3.0)
                density = mass / (radius ** 3)
              end
            when (41..75)
              # Terrestrial

              if planet_roll.in?(41..60)
                # Sub-Earth

                planet_type = PlanetType.find_by(name: 'Sub Earth').id

                mass = Random.rand(0.1..1.0)
                density = Random.rand(0.5..2.0)
                radius = (mass / density)**(1.0/3.0)
              else
                # Super-Earth

                planet_type = PlanetType.find_by(name: 'Super Earth').id

                mass = Random.rand(1.0..10.0)
                density = Random.rand(0.5..2.0)
                radius = (mass / density)**(1.0/3.0)
              end
            when (76..80)
              # Brown Dwarf

              planet_type = PlanetType.find_by(name: 'Brown Dwarf').id

              mass = Random.rand(635..25426)
              radius = 11 + Random.rand
              density = mass / (radius ** 3)
            when (81..90)
              # Asteroid belt

              planet_type = PlanetType.find_by(name: 'Asteroid Belt').id

              mass = Random.rand(0.0001..0.02) * orbit
            else
              # Empty orbit
          end
        else
          # More terrestrials inside of Frost Line

          # TODO Magic Numbers!!!
          case planet_roll
            when (1..10)
              # Gas giant

              if orbit > 0.5
                planet_type = PlanetType.find_by(name: 'Gas Giant').id

                mass = Random.rand(10.0..4132.0)
                radius = Math.log10(10 * mass) + Random.rand(1.5..5.0)

                # Gas giants more massive than 2Mj collapse at 11 Re, so adjust it to max out somewhere around there
                if mass > 635.0
                  if radius > 11.0
                    radius = 10.5 + Random.rand()
                  end
                end
              elsif orbit > 0.04
                # Puffy Giant / Hot Jupiter

                planet_type = PlanetType.find_by(name: 'Puffy Giant').id

                mass = Random.rand(10.0..4132.0)
                radius = radius = Math.log10(10 * mass) + Random.rand(1.5..18.0)

              end

              density = mass / (radius ** 3)
            when (11..70)
              # Terrestrial

              if planet_roll.in?(11..40)
                # Sub-Earth

                planet_type = PlanetType.find_by(name: 'Sub Earth').id

                mass = Random.rand(0.1..1.0)
                density = Random.rand(0.5..2.0)
                radius = (mass / density)**(1.0/3.0)
              else
                # Super-Earth

                planet_type = PlanetType.find_by(name: 'Super Earth').id

                mass = Random.rand(1.0..10.0)
                density = Random.rand(0.5..2.0)
                radius = (mass / density)**(1.0/3.0)
              end
            when (71..85)
              # Asteroid belt

              planet_type = PlanetType.find_by(name: 'Asteroid Belt').id

              mass = Random.rand(0.0001..0.02) * orbit
            when (86..90)
              # Brown Dwarf

              planet_type = PlanetType.find_by(name: 'Brown Dwarf').id

              mass = Random.rand(635..25426)
              radius = 11 + Random.rand
              density = mass / (radius ** 3)
            else
              # Empty orbit
          end
        end

        if mass > 0
          if radius > 0
            surface_area = 4 * Math::PI * (radius ** 2)
          end

          if Random.rand(1..100) <= 75
            #Prograde orbit
            obliquity = Random.rand(0..90)
          else
            #Retrograde orbit
            obliquity = Random.rand(91..180)
          end

          planetary_equilibrium_temperature = System.get_total_star_energy(system, orbit).to_i

=begin
          if planetary_equilibrium_temperature.to_i < 120
            planetary_equilibrium_temperature = 120
          end
=end

          planet = Planet.new(name: system.name + ' ' + orbit.round(2).to_s,
                              system_id: system.id,
                              average_orbit: orbit,
                              eccentricity: eccentricity,
                              mass: mass,
                              radius: radius,
                              density: density,
                              planet_type_id: planet_type,
                              surface_area: surface_area,
                              axial_tilt: obliquity,
                              average_temperature: planetary_equilibrium_temperature)

          planet.save

          # Generate ores
          puts "Generating Ores!" if Rails.env.development?
          Ore.generate_ore(planet)
        end

        if radius > 0
          # Check for moons
          num_moons = 0

          # TODO Magic Numbers!!!
          max_orbit = calculate_hill_sphere(solar_mass, mass, orbit, eccentricity) / 2.0
          min_orbit = calculate_roche_limit(radius, density, density * 0.8) * 0.0000426 #translated to AU from Re

          if min_orbit < max_orbit
            current_orbit = (max_orbit + min_orbit) / 2.0

            moon_chance = 0

            while current_orbit > min_orbit
              moon_chance = Random.rand(0.0..100.0)

              # TODO Magic Numbers!!!
              if moon_chance < (10 * Math.sqrt(mass)) - (5 * num_moons)
                # Generate Moon
                Moon.calculate_moon_info(system, planet, current_orbit)

                num_moons += 1
              end

              current_orbit = current_orbit / Random.rand(1.4..2.0)
            end

            current_orbit = ((max_orbit + min_orbit) / 2.0) * Random.rand(1.4..2.0)

            while current_orbit < max_orbit
              moon_chance = Random.rand(0.0..100.0)

              # TODO Magic Numbers!!!
              if moon_chance < (10 * Math.sqrt(mass)) - (5 * num_moons)
                # Generate Moon
                Moon.calculate_moon_info(system, planet, current_orbit)

                num_moons += 1
              end

              current_orbit = current_orbit * Random.rand(1.4..2.0)
            end
          end
        end
      end
    end

  end

  def self.calculate_hill_sphere(primary, secondary, orbit, eccentricity)
    min_orbit = orbit * (1.0 - eccentricity)
    sphere = (primary / (3 * secondary))**(1.0/3.0)

    min_orbit * sphere
  end

  def self.calculate_roche_limit(primary_radius, primary_density, secondary_density)

app/models/planet_type.rb
class PlanetType < ActiveRecord::Base
  has_many :planets
  has_many :moons
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  # GET /planets
  # GET /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
    @moons = @planet.moons.all
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets
  # POST /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: 'Planet was successfully created.' }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1
  # PATCH/PUT /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: 'Planet was successfully updated.' }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1
  # DELETE /planets/1.json
  def destroy
    @planet.destroy
    respond_to do |format|
      format.html { redirect_to planets_url, notice: 'Planet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planet_params
      params.require(:planet).permit(:system_id, :name, :average_orbit, :eccentricity, :mass, :radius, :density, :planet_type_id)
    end
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/planets/_form.html.erb
<%= form_for(@planet) do |f| %>
  <% if @planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
      <% @planet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :system_id %><br>
    <%= f.number_field :system_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :average_orbit %><br>
    <%= f.text_field :average_orbit %>
  </div>
  <div class="field">
    <%= f.label :eccentricity %><br>
    <%= f.text_field :eccentricity %>
  </div>
  <div class="field">
    <%= f.label :mass %><br>
    <%= f.text_field :mass %>
  </div>
  <div class="field">
    <%= f.label :radius %><br>
    <%= f.text_field :radius %>
  </div>
  <div class="field">
    <%= f.label :density %><br>
    <%= f.text_field :density %>
  </div>
  <div class="field">
    <%= f.label :planet_type_id %><br>
    <%= f.number_field :planet_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planets/_planet.html.erb
<li id="planet-<%= planet.id %>">
  <%= link_to planet.name, planet_path(planet) %>
</li>

app/views/planets/edit.html.erb
<h1>Editing Planet</h1>

<%= render 'form' %>

<%= link_to 'Show', @planet %> |
<%= link_to 'Back', planets_path %>

app/views/planets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Planets</h1>

<table>
  <thead>
    <tr>
      <th>System</th>
      <th>Name</th>
      <th>Average orbit</th>
      <th>Eccentricity</th>
      <th>Mass</th>
      <th>Radius</th>
      <th>Density</th>
      <th>Planet type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |planet| %>
      <tr>
        <td><%= planet.system_id %></td>
        <td><%= planet.name %></td>
        <td><%= planet.average_orbit %></td>
        <td><%= planet.eccentricity %></td>
        <td><%= planet.mass %></td>
        <td><%= planet.radius %></td>
        <td><%= planet.density %></td>
        <td><%= planet.planet_type_id %></td>
        <td><%= link_to 'Show', planet %></td>
        <td><%= link_to 'Edit', edit_planet_path(planet) %></td>
        <td><%= link_to 'Destroy', planet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Planet', new_planet_path %>

app/views/planets/new.html.erb
<h1>New Planet</h1>

<%= render 'form' %>

<%= link_to 'Back', planets_path %>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<% if @planet.system %>
    <p>
      <strong>System:</strong>
      <%= link_to @planet.system.name, system_path(@planet.system) %>
    </p>
<% elsif @planet.parent_planet %>
    <p>
      <strong>Parent Planet:</strong>
      <%= link_to @planet.parent_planet.name, planet_path(@planet.parent_planet) %>
    </p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @planet.name %>
</p>

<p>
  <strong>Average orbit:</strong>
  <%= @planet.average_orbit %>
</p>

<p>
  <strong>Eccentricity:</strong>
  <%= @planet.eccentricity %>
</p>

<p>
  <strong>Mass:</strong>
  <%= @planet.mass %>
</p>

<p>
  <strong>Radius:</strong>
  <%= @planet.radius %>
</p>

<p>
  <strong>Density:</strong>
  <%= @planet.density %>
</p>

<p>
  <strong>Planet type:</strong>
  <%= @planet.planet_type.name %>
</p>

<p>
  <strong>Planetary Equilibrium Temperature:</strong>
  <%= @planet.average_temperature %>
</p>

<% if @planet.moons %>
    <p>
      <strong><%= pluralize(@planet.moons.count, 'Moon') %>:</strong>
    <ol>
      <%= render @moons %>
    </ol>
    </p>
<% end %>

<% if @planet.ores %>
    <p>
      <strong>Ores:</strong>
    </p>

    <ol>
        <% @planet.ores.each do |o| %>
            <li id="<%= o.id %>">
              <%= o.ore_type.name %>: <%= o.size %> tons, <%= o.depth %> M deep, 1:<%= o.strip_ratio %> strip
            </li>
        <% end %>
    </ol>
<% end %>

<%= link_to 'Edit', edit_planet_path(@planet) %>
<% if @planet.system %>|
    <%= link_to 'Back', system_path(@planet.system) %>
<% elsif @planet.parent_planet %>|
    <%= link_to 'Back', planet_path(@planet.parent_planet) %>
<% end %>